# Lecture 2023-02-20
## Numpy arrays
### Exercise 10-a)

In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
a

array([1, 2, 3, 4])

*italicized text*

### Exercise 10-b)

In [5]:
a = np.array(range(1,4+1))
a

array([1, 2, 3, 4])

In [6]:
a = np.arange(1,4+1)
a

array([1, 2, 3, 4])

### Exercise 12-a)

In [14]:
np.random.seed(7548)
a = np.random.randint(2, 30+1, size=3*4)
a = a.reshape(3,4)
a

array([[10,  7, 20, 15],
       [21, 10, 10,  8],
       [13, 20, 10, 19]])

In [15]:
a.sum(axis=1)

array([52, 49, 62])

### Exercise 12-b)

In [16]:
a.sum(axis=0)

array([44, 37, 40, 42])

In [17]:
a.mean(axis=1)

array([13.  , 12.25, 15.5 ])

### Exercise 12-c)

In [20]:
np.sum(True)

1

In [22]:
np.sum(False)

0

In [23]:
np.sum(a > 15, axis=1)

array([1, 1, 2])

### Exercise 11-a)

In [25]:
a = np.array([[1, 2, 3, 4],
          [8,9,6,5]])

a

array([[1, 2, 3, 4],
       [8, 9, 6, 5]])

### Exercise 12-a)

### Exercise 12-b)

### Exercise 12-c)

### Exercise 12-d)

### Exercise 13

![image.png](attachment:image.png)

In [34]:
course1 = [15, 18, 19]
course2 = [18, 19, 14]
course3 = [14, 16, 17]

marks = np.array([course1, course2, course3])
marks = marks.T
marks

credits = np.array([6, 4.5, 3])

np.round(np.sum(marks * credits, axis=1) / np.sum(credits), 2)

array([15.78, 17.89, 16.89])

In [31]:
18*4.5

81.0

### Exercise 14

- To ensure reproducibility, we can set the seed before the random numbers are generated.

- If we are using numpy, we can use: `np.random.seed('an whatever integer number')`

- If we choose the same integer number for seed, then the generated random numbers will be the same for all of us.

### Exercise 14-a)

In [36]:
np.random.seed(124)

a = np.random.randint(2, 30+1, size = 4*2*5)
a = a.reshape(4, 2, 5)
a

array([[[16, 30, 19,  9,  4],
        [11,  2, 22, 22, 30]],

       [[16, 23, 23, 24, 30],
        [29, 11, 24, 16, 18]],

       [[10, 11, 11,  2,  4],
        [20, 19,  3, 11, 15]],

       [[13,  3, 27, 12,  6],
        [28,  3, 21, 23, 24]]])

In [37]:
a.sum(axis=0)

array([[55, 67, 80, 47, 44],
       [88, 35, 70, 72, 87]])

### Exercise 14-b)

In [38]:
a.sum(axis=1)

array([[27, 32, 41, 31, 34],
       [45, 34, 47, 40, 48],
       [30, 30, 14, 13, 19],
       [41,  6, 48, 35, 30]])

### Exercise 14-c)

In [39]:
a.sum(axis=2)

array([[ 78,  87],
       [116,  98],
       [ 38,  68],
       [ 61,  99]])

## Pandas dataframes

### Exercise 16-a)

In [44]:
import pandas as pd

df = pd.DataFrame({'Students': ['John', 'Catherine', 'Mary'],
              'Ages': [18, 30, 25]})

df

    Students  Ages
0       John    18
1  Catherine    30
2       Mary    25

### Exercise 16-b)

## Reading and writing data files

### Exercise 17

In [45]:
df = pd.read_excel('data_carradios.xlsx')
df

     perc_defec      bdate  team  training      datep  prizeq  prized
0          0.00 1981-07-02     8         1 2021-07-01       0       0
1         36.32 1992-06-14     6         0 2021-07-02       0       0
2         48.91 2003-05-28     7         0 2021-07-05     500       0
3         20.36 1992-06-14    10         0 2021-07-06       0       0
4         42.07 2003-05-28     7         0 2021-07-07     500       0
..          ...        ...   ...       ...        ...     ...     ...
995       21.50 1981-07-02     1         0 2021-12-13       0       0
996        7.53 1981-07-02     2         0 2021-12-14     500     600
997       27.70 1997-12-05    10         0 2021-12-15       0       0
998        0.00 1986-12-23     5         0 2021-12-16       0     600
999       38.39 1986-12-23     6         0 2021-12-17       0       0

[1000 rows x 7 columns]

### Exercise 18

In [46]:
df = pd.read_csv('course_marks.csv')
df

               Names  Test 1  Test 2  Test 3
0           Troy Day   12.43   14.13   14.65
1   Daniel Hernandez   13.22   14.47   11.95
2    Michelle Wilson   12.82   16.11   14.95
3         Sarah Moon   13.68   15.36   16.61
4       Devin Carter   13.28   15.77   15.46
5       John Griffin   14.97   16.13   14.81
6         Maria Gray   12.89   19.02   14.06
7    William Mcclure   14.06   16.47   14.32
8       Darrell King   10.21   15.13   14.20
9     Valerie Holder   15.58   15.38   16.66
10   Brandon Mullins   14.17   17.35   14.97
11   Makayla Whitney   15.86   19.20   18.45
12     David Higgins   13.73   15.41   13.81
13       Samuel Vega   13.39   18.90   15.70
14     Melissa Berry   17.61   18.39   16.60
15   Brandon Johnson   13.36   17.44   17.64
16        Ryan Weber   15.58   19.56   17.17
17     Karen Stanley   13.12   17.72   14.89
18       Ryan Spence   14.41   16.79   15.89
19     Ryan Harrison   13.10   17.23   15.67

### Exercise 19

### Exercise 20

## Functions

```
def name_of_function(parameters):
  line of code
  line of code
  line of code
  ...
  return result
```

### Exercise 21-a)

In [47]:
def calc_score(t1, t2, t3):
  score = t1*0.25 + t2*0.4 + t3*0.35
  return score

In [48]:
calc_score(15, 18, 12)

15.149999999999999

In [55]:
df['Score'] = [calc_score(x[0], x[1], x[2]) for x in zip(df['Test 1'], df['Test 2'], df['Test 3'])]

In [56]:
df

               Names  Test 1  Test 2  Test 3    Score
0           Troy Day   12.43   14.13   14.65  13.8870
1   Daniel Hernandez   13.22   14.47   11.95  13.2755
2    Michelle Wilson   12.82   16.11   14.95  14.8815
3         Sarah Moon   13.68   15.36   16.61  15.3775
4       Devin Carter   13.28   15.77   15.46  15.0390
5       John Griffin   14.97   16.13   14.81  15.3780
6         Maria Gray   12.89   19.02   14.06  15.7515
7    William Mcclure   14.06   16.47   14.32  15.1150
8       Darrell King   10.21   15.13   14.20  13.5745
9     Valerie Holder   15.58   15.38   16.66  15.8780
10   Brandon Mullins   14.17   17.35   14.97  15.7220
11   Makayla Whitney   15.86   19.20   18.45  18.1025
12     David Higgins   13.73   15.41   13.81  14.4300
13       Samuel Vega   13.39   18.90   15.70  16.4025
14     Melissa Berry   17.61   18.39   16.60  17.5685
15   Brandon Johnson   13.36   17.44   17.64  16.4900
16        Ryan Weber   15.58   19.56   17.17  17.7285
17     Karen Stanley   13.12   17.72   14.89  15.5795
18       Ryan Spence   14.41   16.79   15.89  15.8800
19     Ryan Harrison   13.10   17.23   15.67  15.6515

### Exercise 21-b)

In [60]:
df['Score2'] = df['Test 1'].mul(0.25)+df['Test 2'].mul(0.4) + df['Test 3'].mul(0.35)

In [61]:
df

               Names  Test 1  Test 2  Test 3    Score   Score2
0           Troy Day   12.43   14.13   14.65  13.8870  13.8870
1   Daniel Hernandez   13.22   14.47   11.95  13.2755  13.2755
2    Michelle Wilson   12.82   16.11   14.95  14.8815  14.8815
3         Sarah Moon   13.68   15.36   16.61  15.3775  15.3775
4       Devin Carter   13.28   15.77   15.46  15.0390  15.0390
5       John Griffin   14.97   16.13   14.81  15.3780  15.3780
6         Maria Gray   12.89   19.02   14.06  15.7515  15.7515
7    William Mcclure   14.06   16.47   14.32  15.1150  15.1150
8       Darrell King   10.21   15.13   14.20  13.5745  13.5745
9     Valerie Holder   15.58   15.38   16.66  15.8780  15.8780
10   Brandon Mullins   14.17   17.35   14.97  15.7220  15.7220
11   Makayla Whitney   15.86   19.20   18.45  18.1025  18.1025
12     David Higgins   13.73   15.41   13.81  14.4300  14.4300
13       Samuel Vega   13.39   18.90   15.70  16.4025  16.4025
14     Melissa Berry   17.61   18.39   16.60  17.5685  17.5685
15   Brandon Johnson   13.36   17.44   17.64  16.4900  16.4900
16        Ryan Weber   15.58   19.56   17.17  17.7285  17.7285
17     Karen Stanley   13.12   17.72   14.89  15.5795  15.5795
18       Ryan Spence   14.41   16.79   15.89  15.8800  15.8800
19     Ryan Harrison   13.10   17.23   15.67  15.6515  15.6515

### Exercise 21-c)

## Plots

### Line plot

### Exercise 1

- `np.linspace(start_interval, end_interval, number of points)`:

  It returns evenly spaced numbers over a specified interval.

### Scatter plot

- Scatter plots are useful for inferring the existence of a *relationship* between two variables

### Exercise 3

### Exercise 4

- To use `seaborn`, we need to create a dataframe with the data.

### Exercise 5

### Boxplot

- It shows where quartiles of a variable are.

- It is useful for detecting outliers.

![image.png](attachment:image.png){width="20%" height="20%"}

### Exercise 6

### Exercise 7

### Histograms

- Histograms are useful for visualizing the *distribution* of a variable.

### Exercise 8

### Exercise 9